version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: inbox-zero-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: inboxzero
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-inbox_zero_secure_password}
    volumes:
      - inbox_zero_db_data:/var/lib/postgresql/data
    networks:
      - web
      - inbox-zero-network
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: inbox-zero-redis
    volumes:
      - inbox_zero_redis_data:/data
    networks:
      - inbox-zero-network
    labels:
      - "traefik.enable=false"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    restart: unless-stopped
    container_name: inbox-zero-redis-http
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${UPSTASH_REDIS_TOKEN}
      SRH_CONNECTION_STRING: "redis://redis:6379"
    networks:
      - inbox-zero-network
    labels:
      - "traefik.enable=false"
    depends_on:
      - redis

  web:
    image: ghcr.io/elie222/inbox-zero:latest
    restart: unless-stopped
    container_name: inbox-zero-web
    environment:
      # Database
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-inbox_zero_secure_password}@db:5432/inboxzero?schema=public"
      DIRECT_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-inbox_zero_secure_password}@db:5432/inboxzero?schema=public"
      
      # NextAuth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: https://inbox-zero.taft-ranch.com
      
      # Google APIs
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_ENCRYPT_SECRET: ${GOOGLE_ENCRYPT_SECRET}
      GOOGLE_ENCRYPT_SALT: ${GOOGLE_ENCRYPT_SALT}
      
      # Redis
      UPSTASH_REDIS_URL: "http://serverless-redis-http:80"
      UPSTASH_REDIS_TOKEN: ${UPSTASH_REDIS_TOKEN}
      
      # LLM (use Claude since you have access)
      DEFAULT_LLM_PROVIDER: anthropic
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      
      # Internal API
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      API_KEY_SALT: ${API_KEY_SALT}
      
      # App configuration
      NEXT_PUBLIC_APP_HOME_PATH: /assistant
      LOG_ZOD_ERRORS: true
      
    depends_on:
      - db
      - redis
      - serverless-redis-http
    networks:
      - web
      - inbox-zero-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inbox-zero.rule=Host(`inbox-zero.taft-ranch.com`)"
      - "traefik.http.routers.inbox-zero.tls=true"
      - "traefik.http.routers.inbox-zero.tls.certresolver=cloudflare"
      - "traefik.http.services.inbox-zero.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"

volumes:
  inbox_zero_db_data:
    driver: local
  inbox_zero_redis_data:
    driver: local

networks:
  web:
    external: true
  inbox-zero-network:
    driver: bridge